create table "public"."emplyees" (
                                     "id" bigint generated by default as identity not null,
                                     "created_at" timestamp with time zone not null default now(),
                                     "name" text
);

alter table "public"."emplyees" enable row level security;

create unique index emplyees_pkey
    on public.emplyees using btree (id);

alter table "public"."emplyees"
    add constraint "emplyees_pkey"
        primary key using index "emplyees_pkey";

grant delete on table "public"."emplyees" to "anon";
grant insert on table "public"."emplyees" to "anon";
grant references on table "public"."emplyees" to "anon";
grant select on table "public"."emplyees" to "anon";
grant trigger on table "public"."emplyees" to "anon";
grant truncate on table "public"."emplyees" to "anon";
grant update on table "public"."emplyees" to "anon";

grant delete on table "public"."emplyees" to "authenticated";
grant insert on table "public"."emplyees" to "authenticated";
grant references on table "public"."emplyees" to "authenticated";
grant select on table "public"."emplyees" to "authenticated";
grant trigger on table "public"."emplyees" to "authenticated";
grant truncate on table "public"."emplyees" to "authenticated";
grant update on table "public"."emplyees" to "authenticated";

grant delete on table "public"."emplyees" to "postgres";
grant insert on table "public"."emplyees" to "postgres";
grant references on table "public"."emplyees" to "postgres";
grant select on table "public"."emplyees" to "postgres";
grant trigger on table "public"."emplyees" to "postgres";
grant truncate on table "public"."emplyees" to "postgres";
grant update on table "public"."emplyees" to "postgres";

grant delete on table "public"."emplyees" to "service_role";
grant insert on table "public"."emplyees" to "service_role";
grant references on table "public"."emplyees" to "service_role";
grant select on table "public"."emplyees" to "service_role";
grant trigger on table "public"."emplyees" to "service_role";
grant truncate on table "public"."emplyees" to "service_role";
grant update on table "public"."emplyees" to "service_role";
